
services:
  mongo:
    image: mongo:7
    container_name: mongo-todo
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

  Redis:
    image: redis:8-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis
    restart: on-failure




volumes:
  mongodb-data:
  redis_data: